export const TYPES = {
  IUser: Symbol.for("IUser"),
  ITask: Symbol.for("ITask"),
  IUserRepo: Symbol.for("IUserRepo"),
  ITaskRepo: Symbol.for("ITaskRepo"),
  IUserService: Symbol.for("IUserService"),
  IAuthService: Symbol.for("IAuthService"),
  INotificationService: Symbol.for("INotificationService"),
  ITaskService: Symbol.for("ITaskService"),
  IPasswordService: Symbol.for("IPasswordService"),
  IRedisRepo: Symbol.for("IRedisRepo"),
  IOtpService: Symbol.for("IOtpService"),
  ITokenService: Symbol.for("ITokenService"),
  IEmailService: Symbol.for("IEmailService"),
  AuthController: Symbol.for("AuthController"),
  IAuthMiddleware: Symbol.for("IAuthMiddleware"),
  TaskController: Symbol.for("TaskController"),
};
